const metadata = data?.roll?.metadata;
const role = metadata?.role;
const method = metadata?.method;
const stat = metadata?.stat; // For individual stat rolls in Edgerunner method
const roll = data?.roll?.total;

// Helper function to capitalize strings
function capitalize(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
}

// Stat tables for each role (Streetrats/Edgerunner method)
const statTables = {
  tech: [
    {
      roll: 1,
      int: 6,
      ref: 7,
      dex: 7,
      tech: 8,
      cool: 4,
      will: 4,
      luck: 5,
      move: 5,
      body: 7,
      emp: 6,
    },
    {
      roll: 2,
      int: 7,
      ref: 6,
      dex: 6,
      tech: 7,
      cool: 5,
      will: 3,
      luck: 7,
      move: 7,
      body: 5,
      emp: 5,
    },
    {
      roll: 3,
      int: 8,
      ref: 6,
      dex: 5,
      tech: 7,
      cool: 5,
      will: 4,
      luck: 7,
      move: 7,
      body: 5,
      emp: 7,
    },
    {
      roll: 4,
      int: 7,
      ref: 8,
      dex: 7,
      tech: 8,
      cool: 4,
      will: 4,
      luck: 6,
      move: 5,
      body: 6,
      emp: 7,
    },
    {
      roll: 5,
      int: 6,
      ref: 6,
      dex: 7,
      tech: 6,
      cool: 4,
      will: 3,
      luck: 7,
      move: 7,
      body: 6,
      emp: 6,
    },
    {
      roll: 6,
      int: 8,
      ref: 7,
      dex: 5,
      tech: 6,
      cool: 3,
      will: 3,
      luck: 7,
      move: 6,
      body: 6,
      emp: 7,
    },
    {
      roll: 7,
      int: 8,
      ref: 6,
      dex: 7,
      tech: 8,
      cool: 4,
      will: 4,
      luck: 7,
      move: 6,
      body: 7,
      emp: 6,
    },
    {
      roll: 8,
      int: 8,
      ref: 8,
      dex: 7,
      tech: 8,
      cool: 5,
      will: 4,
      luck: 6,
      move: 5,
      body: 6,
      emp: 6,
    },
    {
      roll: 9,
      int: 6,
      ref: 6,
      dex: 7,
      tech: 8,
      cool: 3,
      will: 3,
      luck: 5,
      move: 7,
      body: 7,
      emp: 7,
    },
    {
      roll: 10,
      int: 8,
      ref: 8,
      dex: 5,
      tech: 6,
      cool: 4,
      will: 4,
      luck: 6,
      move: 5,
      body: 6,
      emp: 6,
    },
  ],
  solo: [
    {
      roll: 1,
      int: 6,
      ref: 7,
      dex: 7,
      tech: 3,
      cool: 8,
      will: 6,
      luck: 5,
      move: 5,
      body: 6,
      emp: 5,
    },
    {
      roll: 2,
      int: 7,
      ref: 8,
      dex: 6,
      tech: 3,
      cool: 6,
      will: 6,
      luck: 7,
      move: 5,
      body: 6,
      emp: 6,
    },
    {
      roll: 3,
      int: 5,
      ref: 8,
      dex: 7,
      tech: 4,
      cool: 7,
      will: 7,
      luck: 6,
      move: 7,
      body: 8,
      emp: 5,
    },
    {
      roll: 4,
      int: 5,
      ref: 8,
      dex: 6,
      tech: 4,
      cool: 6,
      will: 7,
      luck: 6,
      move: 5,
      body: 7,
      emp: 6,
    },
    {
      roll: 5,
      int: 6,
      ref: 6,
      dex: 7,
      tech: 5,
      cool: 7,
      will: 6,
      luck: 7,
      move: 6,
      body: 8,
      emp: 4,
    },
    {
      roll: 6,
      int: 7,
      ref: 7,
      dex: 6,
      tech: 5,
      cool: 7,
      will: 6,
      luck: 6,
      move: 7,
      body: 7,
      emp: 5,
    },
    {
      roll: 7,
      int: 7,
      ref: 7,
      dex: 6,
      tech: 5,
      cool: 6,
      will: 7,
      luck: 7,
      move: 6,
      body: 6,
      emp: 6,
    },
    {
      roll: 8,
      int: 7,
      ref: 8,
      dex: 7,
      tech: 5,
      cool: 6,
      will: 6,
      luck: 5,
      move: 6,
      body: 8,
      emp: 4,
    },
    {
      roll: 9,
      int: 7,
      ref: 7,
      dex: 6,
      tech: 4,
      cool: 6,
      will: 6,
      luck: 6,
      move: 5,
      body: 6,
      emp: 5,
    },
    {
      roll: 10,
      int: 6,
      ref: 6,
      dex: 8,
      tech: 5,
      cool: 6,
      will: 6,
      luck: 5,
      move: 6,
      body: 6,
      emp: 5,
    },
  ],
  rockerboy: [
    {
      roll: 1,
      int: 7,
      ref: 6,
      dex: 6,
      tech: 5,
      cool: 6,
      will: 8,
      luck: 7,
      move: 7,
      body: 3,
      emp: 8,
    },
    {
      roll: 2,
      int: 3,
      ref: 7,
      dex: 7,
      tech: 7,
      cool: 7,
      will: 6,
      luck: 7,
      move: 7,
      body: 5,
      emp: 8,
    },
    {
      roll: 3,
      int: 4,
      ref: 5,
      dex: 7,
      tech: 7,
      cool: 6,
      will: 6,
      luck: 7,
      move: 7,
      body: 5,
      emp: 8,
    },
    {
      roll: 4,
      int: 4,
      ref: 5,
      dex: 7,
      tech: 7,
      cool: 6,
      will: 8,
      luck: 7,
      move: 6,
      body: 3,
      emp: 8,
    },
    {
      roll: 5,
      int: 3,
      ref: 7,
      dex: 7,
      tech: 7,
      cool: 6,
      will: 8,
      luck: 6,
      move: 5,
      body: 4,
      emp: 7,
    },
    {
      roll: 6,
      int: 5,
      ref: 6,
      dex: 7,
      tech: 5,
      cool: 7,
      will: 8,
      luck: 5,
      move: 7,
      body: 3,
      emp: 7,
    },
    {
      roll: 7,
      int: 5,
      ref: 6,
      dex: 6,
      tech: 7,
      cool: 7,
      will: 8,
      luck: 7,
      move: 6,
      body: 3,
      emp: 6,
    },
    {
      roll: 8,
      int: 5,
      ref: 7,
      dex: 7,
      tech: 5,
      cool: 6,
      will: 6,
      luck: 6,
      move: 6,
      body: 4,
      emp: 8,
    },
    {
      roll: 9,
      int: 3,
      ref: 5,
      dex: 5,
      tech: 6,
      cool: 7,
      will: 8,
      luck: 7,
      move: 5,
      body: 5,
      emp: 7,
    },
    {
      roll: 10,
      int: 4,
      ref: 5,
      dex: 6,
      tech: 5,
      cool: 8,
      will: 8,
      luck: 7,
      move: 6,
      body: 4,
      emp: 7,
    },
  ],
  nomad: [
    {
      roll: 1,
      int: 6,
      ref: 6,
      dex: 8,
      tech: 3,
      cool: 6,
      will: 7,
      luck: 6,
      move: 6,
      body: 6,
      emp: 4,
    },
    {
      roll: 2,
      int: 5,
      ref: 7,
      dex: 6,
      tech: 5,
      cool: 8,
      will: 8,
      luck: 8,
      move: 7,
      body: 5,
      emp: 4,
    },
    {
      roll: 3,
      int: 5,
      ref: 8,
      dex: 6,
      tech: 3,
      cool: 8,
      will: 7,
      luck: 6,
      move: 5,
      body: 6,
      emp: 5,
    },
    {
      roll: 4,
      int: 5,
      ref: 8,
      dex: 7,
      tech: 4,
      cool: 8,
      will: 6,
      luck: 7,
      move: 7,
      body: 7,
      emp: 5,
    },
    {
      roll: 5,
      int: 6,
      ref: 6,
      dex: 6,
      tech: 3,
      cool: 6,
      will: 7,
      luck: 6,
      move: 7,
      body: 7,
      emp: 4,
    },
    {
      roll: 6,
      int: 7,
      ref: 6,
      dex: 8,
      tech: 4,
      cool: 6,
      will: 7,
      luck: 6,
      move: 5,
      body: 6,
      emp: 5,
    },
    {
      roll: 7,
      int: 6,
      ref: 7,
      dex: 8,
      tech: 4,
      cool: 6,
      will: 6,
      luck: 7,
      move: 5,
      body: 7,
      emp: 5,
    },
    {
      roll: 8,
      int: 5,
      ref: 7,
      dex: 8,
      tech: 3,
      cool: 8,
      will: 6,
      luck: 7,
      move: 5,
      body: 5,
      emp: 5,
    },
    {
      roll: 9,
      int: 6,
      ref: 7,
      dex: 6,
      tech: 4,
      cool: 8,
      will: 6,
      luck: 6,
      move: 6,
      body: 6,
      emp: 6,
    },
    {
      roll: 10,
      int: 5,
      ref: 6,
      dex: 7,
      tech: 4,
      cool: 7,
      will: 8,
      luck: 7,
      move: 7,
      body: 7,
      emp: 4,
    },
  ],
  netrunner: [
    {
      roll: 1,
      int: 5,
      ref: 8,
      dex: 7,
      tech: 7,
      cool: 7,
      will: 4,
      luck: 8,
      move: 7,
      body: 7,
      emp: 4,
    },
    {
      roll: 2,
      int: 5,
      ref: 6,
      dex: 7,
      tech: 5,
      cool: 8,
      will: 3,
      luck: 8,
      move: 7,
      body: 5,
      emp: 5,
    },
    {
      roll: 3,
      int: 5,
      ref: 6,
      dex: 8,
      tech: 6,
      cool: 6,
      will: 4,
      luck: 7,
      move: 6,
      body: 7,
      emp: 4,
    },
    {
      roll: 4,
      int: 5,
      ref: 7,
      dex: 7,
      tech: 7,
      cool: 7,
      will: 5,
      luck: 8,
      move: 6,
      body: 5,
      emp: 5,
    },
    {
      roll: 5,
      int: 5,
      ref: 8,
      dex: 8,
      tech: 5,
      cool: 7,
      will: 3,
      luck: 7,
      move: 5,
      body: 5,
      emp: 6,
    },
    {
      roll: 6,
      int: 6,
      ref: 6,
      dex: 6,
      tech: 7,
      cool: 8,
      will: 4,
      luck: 7,
      move: 7,
      body: 6,
      emp: 6,
    },
    {
      roll: 7,
      int: 6,
      ref: 6,
      dex: 6,
      tech: 7,
      cool: 6,
      will: 5,
      luck: 7,
      move: 7,
      body: 7,
      emp: 6,
    },
    {
      roll: 8,
      int: 5,
      ref: 7,
      dex: 8,
      tech: 6,
      cool: 8,
      will: 4,
      luck: 8,
      move: 5,
      body: 7,
      emp: 4,
    },
    {
      roll: 9,
      int: 7,
      ref: 6,
      dex: 7,
      tech: 7,
      cool: 6,
      will: 3,
      luck: 6,
      move: 5,
      body: 6,
      emp: 5,
    },
    {
      roll: 10,
      int: 7,
      ref: 8,
      dex: 6,
      tech: 6,
      cool: 6,
      will: 4,
      luck: 7,
      move: 7,
      body: 5,
      emp: 6,
    },
  ],
  medtech: [
    {
      roll: 1,
      int: 7,
      ref: 5,
      dex: 6,
      tech: 7,
      cool: 5,
      will: 3,
      luck: 8,
      move: 5,
      body: 5,
      emp: 7,
    },
    {
      roll: 2,
      int: 6,
      ref: 7,
      dex: 7,
      tech: 7,
      cool: 4,
      will: 4,
      luck: 6,
      move: 7,
      body: 7,
      emp: 7,
    },
    {
      roll: 3,
      int: 6,
      ref: 5,
      dex: 5,
      tech: 8,
      cool: 5,
      will: 3,
      luck: 8,
      move: 5,
      body: 7,
      emp: 8,
    },
    {
      roll: 4,
      int: 8,
      ref: 7,
      dex: 6,
      tech: 8,
      cool: 3,
      will: 5,
      luck: 6,
      move: 6,
      body: 5,
      emp: 7,
    },
    {
      roll: 5,
      int: 6,
      ref: 7,
      dex: 5,
      tech: 7,
      cool: 5,
      will: 5,
      luck: 8,
      move: 7,
      body: 6,
      emp: 8,
    },
    {
      roll: 6,
      int: 8,
      ref: 5,
      dex: 5,
      tech: 8,
      cool: 5,
      will: 5,
      luck: 6,
      move: 6,
      body: 5,
      emp: 6,
    },
    {
      roll: 7,
      int: 8,
      ref: 6,
      dex: 5,
      tech: 8,
      cool: 5,
      will: 4,
      luck: 8,
      move: 5,
      body: 7,
      emp: 7,
    },
    {
      roll: 8,
      int: 6,
      ref: 5,
      dex: 7,
      tech: 7,
      cool: 3,
      will: 5,
      luck: 8,
      move: 5,
      body: 5,
      emp: 8,
    },
    {
      roll: 9,
      int: 6,
      ref: 6,
      dex: 7,
      tech: 7,
      cool: 5,
      will: 4,
      luck: 6,
      move: 6,
      body: 5,
      emp: 6,
    },
    {
      roll: 10,
      int: 8,
      ref: 7,
      dex: 6,
      tech: 6,
      cool: 3,
      will: 4,
      luck: 8,
      move: 7,
      body: 6,
      emp: 7,
    },
  ],
  media: [
    {
      roll: 1,
      int: 6,
      ref: 6,
      dex: 5,
      tech: 5,
      cool: 8,
      will: 7,
      luck: 5,
      move: 7,
      body: 5,
      emp: 7,
    },
    {
      roll: 2,
      int: 8,
      ref: 7,
      dex: 7,
      tech: 3,
      cool: 6,
      will: 6,
      luck: 6,
      move: 5,
      body: 6,
      emp: 8,
    },
    {
      roll: 3,
      int: 6,
      ref: 7,
      dex: 7,
      tech: 5,
      cool: 6,
      will: 8,
      luck: 5,
      move: 5,
      body: 5,
      emp: 7,
    },
    {
      roll: 4,
      int: 6,
      ref: 5,
      dex: 7,
      tech: 5,
      cool: 6,
      will: 7,
      luck: 5,
      move: 5,
      body: 6,
      emp: 6,
    },
    {
      roll: 5,
      int: 6,
      ref: 6,
      dex: 7,
      tech: 4,
      cool: 8,
      will: 7,
      luck: 6,
      move: 7,
      body: 5,
      emp: 8,
    },
    {
      roll: 6,
      int: 7,
      ref: 5,
      dex: 5,
      tech: 4,
      cool: 8,
      will: 7,
      luck: 6,
      move: 7,
      body: 5,
      emp: 8,
    },
    {
      roll: 7,
      int: 8,
      ref: 5,
      dex: 6,
      tech: 3,
      cool: 7,
      will: 6,
      luck: 6,
      move: 5,
      body: 6,
      emp: 7,
    },
    {
      roll: 8,
      int: 6,
      ref: 5,
      dex: 6,
      tech: 5,
      cool: 6,
      will: 8,
      luck: 6,
      move: 6,
      body: 7,
      emp: 8,
    },
    {
      roll: 9,
      int: 7,
      ref: 7,
      dex: 5,
      tech: 4,
      cool: 6,
      will: 7,
      luck: 6,
      move: 5,
      body: 6,
      emp: 7,
    },
    {
      roll: 10,
      int: 7,
      ref: 6,
      dex: 6,
      tech: 3,
      cool: 7,
      will: 6,
      luck: 7,
      move: 6,
      body: 7,
      emp: 6,
    },
  ],
  lawman: [
    {
      roll: 1,
      int: 5,
      ref: 6,
      dex: 7,
      tech: 5,
      cool: 7,
      will: 8,
      luck: 5,
      move: 6,
      body: 5,
      emp: 6,
    },
    {
      roll: 2,
      int: 6,
      ref: 6,
      dex: 6,
      tech: 5,
      cool: 6,
      will: 8,
      luck: 5,
      move: 7,
      body: 5,
      emp: 5,
    },
    {
      roll: 3,
      int: 5,
      ref: 7,
      dex: 7,
      tech: 7,
      cool: 6,
      will: 7,
      luck: 5,
      move: 5,
      body: 7,
      emp: 6,
    },
    {
      roll: 4,
      int: 6,
      ref: 6,
      dex: 7,
      tech: 6,
      cool: 6,
      will: 8,
      luck: 5,
      move: 7,
      body: 7,
      emp: 6,
    },
    {
      roll: 5,
      int: 6,
      ref: 6,
      dex: 7,
      tech: 6,
      cool: 7,
      will: 7,
      luck: 6,
      move: 5,
      body: 5,
      emp: 6,
    },
    {
      roll: 6,
      int: 7,
      ref: 6,
      dex: 5,
      tech: 5,
      cool: 7,
      will: 8,
      luck: 5,
      move: 6,
      body: 7,
      emp: 4,
    },
    {
      roll: 7,
      int: 7,
      ref: 8,
      dex: 7,
      tech: 5,
      cool: 6,
      will: 8,
      luck: 7,
      move: 6,
      body: 5,
      emp: 4,
    },
    {
      roll: 8,
      int: 5,
      ref: 6,
      dex: 6,
      tech: 5,
      cool: 6,
      will: 8,
      luck: 5,
      move: 7,
      body: 6,
      emp: 4,
    },
    {
      roll: 9,
      int: 7,
      ref: 7,
      dex: 5,
      tech: 5,
      cool: 7,
      will: 7,
      luck: 6,
      move: 5,
      body: 5,
      emp: 6,
    },
    {
      roll: 10,
      int: 6,
      ref: 6,
      dex: 5,
      tech: 6,
      cool: 8,
      will: 7,
      luck: 5,
      move: 7,
      body: 6,
      emp: 6,
    },
  ],
  fixer: [
    {
      roll: 1,
      int: 8,
      ref: 5,
      dex: 7,
      tech: 4,
      cool: 6,
      will: 5,
      luck: 8,
      move: 5,
      body: 5,
      emp: 8,
    },
    {
      roll: 2,
      int: 8,
      ref: 5,
      dex: 5,
      tech: 5,
      cool: 6,
      will: 7,
      luck: 8,
      move: 7,
      body: 5,
      emp: 7,
    },
    {
      roll: 3,
      int: 6,
      ref: 6,
      dex: 6,
      tech: 4,
      cool: 5,
      will: 6,
      luck: 8,
      move: 6,
      body: 3,
      emp: 8,
    },
    {
      roll: 4,
      int: 7,
      ref: 7,
      dex: 5,
      tech: 5,
      cool: 7,
      will: 6,
      luck: 7,
      move: 7,
      body: 5,
      emp: 8,
    },
    {
      roll: 5,
      int: 8,
      ref: 6,
      dex: 6,
      tech: 3,
      cool: 6,
      will: 5,
      luck: 8,
      move: 7,
      body: 5,
      emp: 6,
    },
    {
      roll: 6,
      int: 8,
      ref: 7,
      dex: 5,
      tech: 5,
      cool: 6,
      will: 7,
      luck: 7,
      move: 5,
      body: 3,
      emp: 6,
    },
    {
      roll: 7,
      int: 8,
      ref: 6,
      dex: 6,
      tech: 5,
      cool: 6,
      will: 5,
      luck: 6,
      move: 7,
      body: 5,
      emp: 8,
    },
    {
      roll: 8,
      int: 6,
      ref: 6,
      dex: 7,
      tech: 4,
      cool: 7,
      will: 6,
      luck: 7,
      move: 7,
      body: 4,
      emp: 7,
    },
    {
      roll: 9,
      int: 8,
      ref: 7,
      dex: 7,
      tech: 5,
      cool: 5,
      will: 5,
      luck: 7,
      move: 6,
      body: 5,
      emp: 7,
    },
    {
      roll: 10,
      int: 6,
      ref: 5,
      dex: 6,
      tech: 5,
      cool: 5,
      will: 6,
      luck: 8,
      move: 6,
      body: 4,
      emp: 7,
    },
  ],
  exec: [
    {
      roll: 1,
      int: 8,
      ref: 5,
      dex: 5,
      tech: 3,
      cool: 8,
      will: 6,
      luck: 6,
      move: 5,
      body: 5,
      emp: 7,
    },
    {
      roll: 2,
      int: 8,
      ref: 6,
      dex: 6,
      tech: 4,
      cool: 7,
      will: 6,
      luck: 7,
      move: 7,
      body: 5,
      emp: 7,
    },
    {
      roll: 3,
      int: 8,
      ref: 7,
      dex: 6,
      tech: 3,
      cool: 8,
      will: 6,
      luck: 7,
      move: 6,
      body: 4,
      emp: 5,
    },
    {
      roll: 4,
      int: 8,
      ref: 5,
      dex: 7,
      tech: 5,
      cool: 6,
      will: 5,
      luck: 6,
      move: 5,
      body: 5,
      emp: 7,
    },
    {
      roll: 5,
      int: 7,
      ref: 7,
      dex: 6,
      tech: 5,
      cool: 8,
      will: 5,
      luck: 7,
      move: 7,
      body: 5,
      emp: 6,
    },
    {
      roll: 6,
      int: 5,
      ref: 7,
      dex: 7,
      tech: 3,
      cool: 6,
      will: 7,
      luck: 6,
      move: 5,
      body: 5,
      emp: 7,
    },
    {
      roll: 7,
      int: 6,
      ref: 6,
      dex: 7,
      tech: 5,
      cool: 8,
      will: 7,
      luck: 6,
      move: 7,
      body: 4,
      emp: 6,
    },
    {
      roll: 8,
      int: 6,
      ref: 7,
      dex: 7,
      tech: 3,
      cool: 7,
      will: 5,
      luck: 7,
      move: 5,
      body: 5,
      emp: 7,
    },
    {
      roll: 9,
      int: 7,
      ref: 6,
      dex: 7,
      tech: 5,
      cool: 7,
      will: 5,
      luck: 7,
      move: 6,
      body: 5,
      emp: 5,
    },
    {
      roll: 10,
      int: 7,
      ref: 7,
      dex: 5,
      tech: 5,
      cool: 8,
      will: 6,
      luck: 6,
      move: 7,
      body: 4,
      emp: 7,
    },
  ],
};

if (!statTables || !statTables[role]) {
  api.showNotification("Error finding stats for roll " + roll, "red", "Error");
  return;
}

const selectedStats = statTables[role].find((entry) => entry.roll === roll);

if (!selectedStats) {
  api.showNotification("Error finding stats for roll " + roll, "red", "Error");
  return;
}

if (method === "streetrat") {
  // Streetrat method: Set all stats at once
  const valuesToSet = {
    "data.wizard.int": selectedStats.int,
    "data.wizard.ref": selectedStats.ref,
    "data.wizard.dex": selectedStats.dex,
    "data.wizard.tech": selectedStats.tech,
    "data.wizard.cool": selectedStats.cool,
    "data.wizard.will": selectedStats.will,
    "data.wizard.luck": selectedStats.luck,
    "data.wizard.move": selectedStats.move,
    "data.wizard.body": selectedStats.body,
    "data.wizard.emp": selectedStats.emp,
  };

  api.setValues(valuesToSet);
  api.sendMessage(
    `Rolled a ${roll} for ${capitalize(role)} using the ${capitalize(
      method
    )} method.`
  );
} else if (method === "edgerunner" && stat) {
  // Edgerunner method: Set individual stat
  const statValue = selectedStats[stat];

  if (statValue === undefined) {
    api.showNotification(
      `Error: Invalid stat "${stat}" for ${role}`,
      "red",
      "Error"
    );
    return;
  }

  const valuesToSet = {};
  valuesToSet[`data.wizard.${stat}`] = statValue;

  api.setValues(valuesToSet);
  api.sendMessage(
    `Rolled a ${roll} for ${stat.toUpperCase()}: ${statValue} (${capitalize(
      role
    )} ${capitalize(method)})`
  );
} else {
  api.showNotification(
    "Invalid method or missing stat parameter",
    "red",
    "Error"
  );
}
